modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
[[mods]]
modId="strange"
version="${version}"
displayName="Strange"
credits=""
authors="svenhjol"
description='''
Charm, but Stranger.
'''
logoFile="icon.png"
[[dependencies.strange]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.strange]]
    modId="charm_api"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.strange]]
    modId="charm_core"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.strange]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
